// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";
import path from "path";
import { app } from "electron";

// Determine database path based on environment
const getDatabasePath = () => {
  if (process.env.NODE_ENV === "production" && app) {
    return path.join(app.getPath("userData"), "laundry.db");
  }
  return path.join(process.cwd(), "prisma", "laundry.db");
};

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `file:${getDatabasePath()}`,
  },
});
